spring.application.name=Voyager

#MongoDB Configuration
spring.data.mongodb.uri=mongodb://10.1.1.65:27017,10.1.1.66:27017,10.1.1.67:27017/voyager?replicaSet=lsmdb
spring.data.mongodb.database=voyager
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.index=DEBUG
logging.level.org.springframework.data.mongodb.core.mapping=DEBUG

app.mongo.strong.read-preference=primary
app.mongo.strong.read-concern=majority
app.mongo.strong.write-concern=majority
app.mongo.strong.journal=true

app.mongo.fast.read-preference=secondaryPreferred
app.mongo.fast.read-concern=local
app.mongo.fast.write-concern=w1
app.mongo.fast.journal=false

#Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#NEO4J CONFIGURATION
<<<<<<< HEAD
spring.neo4j.uri=bolt://10.1.1.70:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=voyager1